### ISSUE TITLE
Platform mismatch when specifying platforms not including the host

### ISSUE THREAD

**Issue by eliperkins** [cgrindel/rules_spm#116]
👋  Hiya @cgrindel! Thanks a ton for this project, it's been really interesting to learn how we can use SwiftPM to build products for Bazel to consume. I'm having a bit of a tough time understanding where I'm going wrong getting a target to build for iOS _only_ using `rules_spm`.

### Repro

[I put together a small example module in a fork that illustrates the bug I'm running into](https://github.com/cgrindel/rules_spm/compare/main...eliperkins:ios-package-bug-example).

1. Add `platforms = [".iOS(.v14)"]` to the `spm_repositories` invocation in the `WORKSPACE`
2. Add a Swift package that includes platforms within it's package description, like [`apollographql/apollo-ios`](https://github.com/apollographql/apollo-ios)
3. Build the module with `bazel build //Sources:Foo`

### Expected Behavior

The `bazel build` invocation builds the SwiftPM target only for the given platforms (in this case, iOS), since there's no need to build dependent modules for other platforms.

### Actual Behavior

The following error is thrown from the SwiftPM invocation

```
error: the library 'Placeholder' requires macos 10.10, but depends on the product 'Apollo' which requires macos 10.14; consider changing the library 'Placeholder' to require macos 10.14 or later, or the product 'Apollo' to require macos 10.10 or earlier.
```

<details>
<summary>Verbose output</summary>

```
❯ bazel build //Sources:Foo --sandbox_debug
INFO: Analyzed target //Sources:Foo (24 packages loaded, 1765 targets configured).
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_eliperkins/0e5e28979b49af89fb8d84a6e03e62ba/external/swift_pkgs/BUILD.bazel:644:12: Building Swift package (external/swift_pkgs) for x86_64-apple-macosx12.1 using SPM. failed: (Exit 1): sandbox-exec failed: error executing command
  (cd /private/var/tmp/_bazel_eliperkins/0e5e28979b49af89fb8d84a6e03e62ba/sandbox/darwin-sandbox/269/execroot/ios_app && \
  exec env - \
    DEVELOPER_DIR=/Applications/Xcode-13.2.1.app/Contents/Developer \
    TMPDIR=/var/folders/v0/4yqzqdxd6j13p6kl5c8qwlhh0000gn/T/ \
    XCODE_VERSION_OVERRIDE=13.2.1.13C100 \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_eliperkins/0e5e28979b49af89fb8d84a6e03e62ba/sandbox/darwin-sandbox/269/sandbox.sb /var/tmp/_bazel_eliperkins/install/0c7899cb691a00c6ca493ede5765e1af/process-wrapper '--timeout=0' '--kill_delay=15' bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/cgrindel_rules_spm/spm/private/exec_spm_build --worker bazel-out/host/bin/external/build_bazel_rules_swift/tools/worker/worker --sdk_name macosx --spm_utility external/cgrindel_rules_spm_local_config/spm_utilities/git -Xspm --disable-sandbox -Xspm --configuration -Xspm release -Xspm --manifest-cache -Xspm none -Xspm --disable-repository-cache -Xswiftc -target -Xswiftc x86_64-apple-macosx12.1 -Xcc -target -Xcc x86_64-apple-macosx12.1 --package-path external/swift_pkgs --build-path bazel-out/darwin-fastbuild/bin/external/swift_pkgs/spm_build external/swift_pkgs/spm_build/checkouts/SQLite.swift/Sources/SQLiteObjc/include/SQLiteObjc.h bazel-out/darwin-fastbuild/bin/external/swift_pkgs/spm_build/x86_64-apple-macosx/release/SQLiteObjc.build/SQLiteObjc.h bazel-out/darwin-fastbuild/bin/external/swift_pkgs/modulemaps/SQLiteObjc.build/module.modulemap bazel-out/darwin-fastbuild/bin/external/swift_pkgs/spm_build/x86_64-apple-macosx/release/SQLiteObjc.build/module.modulemap)
error: the library 'Placeholder' requires macos 10.10, but depends on the product 'Apollo' which requires macos 10.14; consider changing the library 'Placeholder' to require macos 10.14 or later, or the product 'Apollo' to require macos 10.10 or earlier.
Target //Sources:Foo failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /Users/eliperkins/src/rules_spm/examples/ios_app/Sources/BUILD.bazel:3:14 Compiling Swift module //Sources:Foo failed: (Exit 1): sandbox-exec failed: error executing command
  (cd /private/var/tmp/_bazel_eliperkins/0e5e28979b49af89fb8d84a6e03e62ba/sandbox/darwin-sandbox/269/execroot/ios_app && \
  exec env - \
    DEVELOPER_DIR=/Applications/Xcode-13.2.1.app/Contents/Developer \
    TMPDIR=/var/folders/v0/4yqzqdxd6j13p6kl5c8qwlhh0000gn/T/ \
    XCODE_VERSION_OVERRIDE=13.2.1.13C100 \
  /usr/bin/sandbox-exec -f /private/var/tmp/_bazel_eliperkins/0e5e28979b49af89fb8d84a6e03e62ba/sandbox/darwin-sandbox/269/sandbox.sb /var/tmp/_bazel_eliperkins/install/0c7899cb691a00c6ca493ede5765e1af/process-wrapper '--timeout=0' '--kill_delay=15' bazel-out/darwin-opt-exec-2B5CBBC6/bin/external/cgrindel_rules_spm/spm/private/exec_spm_build --worker bazel-out/host/bin/external/build_bazel_rules_swift/tools/worker/worker --sdk_name macosx --spm_utility external/cgrindel_rules_spm_local_config/spm_utilities/git -Xspm --disable-sandbox -Xspm --configuration -Xspm release -Xspm --manifest-cache -Xspm none -Xspm --disable-repository-cache -Xswiftc -target -Xswiftc x86_64-apple-macosx12.1 -Xcc -target -Xcc x86_64-apple-macosx12.1 --package-path external/swift_pkgs --build-path bazel-out/darwin-fastbuild/bin/external/swift_pkgs/spm_build external/swift_pkgs/spm_build/checkouts/SQLite.swift/Sources/SQLiteObjc/include/SQLiteObjc.h bazel-out/darwin-fastbuild/bin/external/swift_pkgs/spm_build/x86_64-apple-macosx/release/SQLiteObjc.build/SQLiteObjc.h bazel-out/darwin-fastbuild/bin/external/swift_pkgs/modulemaps/SQLiteObjc.build/module.modulemap bazel-out/darwin-fastbuild/bin/external/swift_pkgs/spm_build/x86_64-apple-macosx/release/SQLiteObjc.build/module.modulemap)
INFO: Elapsed time: 17.604s, Critical Path: 4.49s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
```

<details>

---

From here, my next step was to add `.macOS(.v10_15)` to work around this issue, which works! I'm not sure if there's something funky going on here that's causing the SwiftPM invocation to build a target which assumes the host platform or something. I'm relatively new to Bazel so forgive me if I'm missing something here!

**Comment by cgrindel** [comment]
Hi, @eliperkins. I believe that you are running into a nuance of Swift PM build platforms. Here are what I think are the relevant statements from [the documentation](https://developer.apple.com/documentation/swift_packages/supportedplatform).

> By default, Xcode assigns a predefined minimum deployment version for each supported platforms unless you configure supported platforms using the platforms API. This predefined deployment version is the oldest deployment target version that the installed SDK supports for a given platform. One exception to this rule is macOS, for which the minimum deployment target version starts from 10.10.

> Xcode emits an error if a dependency isn’t compatible with the top-level package’s deployment version. The deployment target of a package’s dependencies must be lower than or equal to the top-level package’s deployment target version for a particular platform.

Specifically, in the example that you provided, [Apollo specifies `macOS(v10_14)`](https://github.com/apollographql/apollo-ios/blob/main/Package.swift#L10). The supported platforms declaration in your WORKSPACE file does not specify any macOS platform. Swift PM defaults to `macOS(v10_10)`. Since the consumer platform declaration is lower than the dependency's platform declaration, Xcode fails with the error. 

I updated your platforms declaration to include `macOS(v10_14)`.

```python
spm_repositories(
    name = "swift_pkgs",
    dependencies = [
        spm_pkg(
            "https://github.com/apollographql/apollo-ios.git",
            name = "Apollo",
            exact_version = "0.50.0",
            products = ["Apollo"],
        ),
    ],
    platforms = [
        ".iOS(.v14)",
        ".macOS(.v10_14)",
    ],
)
```

I am able to `bazel test //...` the example successfully.

In terms of building for Apple targets, you need to add an appropriate [rules_apple](https://github.com/bazelbuild/rules_apple/tree/master/doc) declaration. There is some magic here. In short, the target platform for the `swift_library` will be influenced by the downstream consumers of that rule. I included the [ios_sim example](https://github.com/cgrindel/rules_spm/tree/main/examples/ios_sim) to demonstrate this technique.

Does that help?

**Comment by eliperkins** [comment]
> One exception to this rule is macOS, for which the minimum deployment target version starts from 10.10. 

Ahhhh, this is totally surprising to me. I didn't notice that in the Apple docs before. Thanks for pointing that out to me. ❤️ 

Totally understood on the `rules_apple` stuff too. I think what was most surprising to me here was that `rules_spm` seemed to be building SwiftPM products for macOS, when the `rules_apple` target that was defined was for an `ios_framework`, so it seemed to me like SwiftPM was building for the _wrong_ platform and linking that into an iOS framework binary, but it seems more that SwiftPM will _overbuild_ for all platforms (because it doesn't support only emitting iOS libraries, as macOS will always be implicitly required).

Thanks for all of this! I'm looking forward to kicking the tires on `rules_spm` some more! Thanks for all your work on this so far.
