### ISSUE TITLE
A clang target must have at least one public header

### ISSUE THREAD

**Issue by pomozoff** [cgrindel/rules_spm#118]
A lot of issues appear when I try to build this package:
```
        spm_pkg(
            url = "https://github.com/SDWebImage/libwebp-Xcode.git",
            from_version = "1.2.1",
            products = ["libwebp"],
        ),
```
1. It has non-standard naming that doesn't match its URL, it leads to errors when **rules_spm** fails to find the package
2. _A clang target must have at least one public header. target: libwebp_ error appears after fixing the first issue

**Comment by cgrindel** [comment]
I have a PR that adds support for nested clang headers. It includes an example that demonstrates how to declare a `libwebp-Xcode`. Because the name of the package does not match the name of the repository, we need to specify the package name using the `name` attribute in `spm_pkg`.
