### ISSUE TITLE
Unable to build certain packages

### ISSUE THREAD

**Issue by sgammon** [cgrindel/rules_spm#128]
Hey there `rules_spm` authors,

Firstly, love this project -- iOS dependencies are tough in Bazel land and this makes it better. Thank you for your hard work on this rule set. I have been using simple Swift packages like [Logging](https://github.com/apple/swift-log) with no issues, but adding more complex Swift packages like [this one](https://github.com/GetStream/stream-swift) seem to produce errors:

```
ERROR: An error occurred during the fetch of repository 'swift_pkgs':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_sam/df355283ea71b0f4452e4b8a830191c8/external/cgrindel_rules_spm/spm/private/spm_repositories.bzl", line 708, column 30, in _spm_repositories_impl
		_configure_spm_repository(repository_ctx, pkgs, env)
	File "/private/var/tmp/_bazel_sam/df355283ea71b0f4452e4b8a830191c8/external/cgrindel_rules_spm/spm/private/spm_repositories.bzl", line 579, column 52, in _configure_spm_repository
		resolve_out = repository_utils.exec_spm_command(
	File "/private/var/tmp/_bazel_sam/df355283ea71b0f4452e4b8a830191c8/external/cgrindel_rules_spm/spm/private/repository_utils.bzl", line 50, column 13, in _execute_spm_command
		fail(err_msg_tpl.format(
Error in fail: Resolution of SPM packages for swift_pkgs failed. args: ["xcrun", "swift", "package", "resolve", "--build-path", "spm_build"]
error: the manifest is missing a Swift tools version specification; consider prepending to the manifest '// swift-tools-version:5.5.0' to specify the current Swift toolchain version as the lowest Swift version supported by the project; if such a specification already exists, consider moving it to the top of the manifest, or prepending it with '//' to help Swift Package Manager find it
```

This error surfaces whether I depend on the Swift package or not; seemingly adding it to the `WORKSPACE` is enough to trigger it. I am happy to provide a repro or sample Swift packages where this occurs

**Comment by cgrindel** [comment]
BTW. What version of Xcode are you using? I will see if I can reproduce this error.

**Comment by cgrindel** [comment]
@sgammon When you get a chance, can you post your `spm_pkg`? I am not seeing the same error that you are seeing. So, I think that there are a couple of issues. 

## My Attempt to Reproduce

I loaded the package using the following declration:

```python
spm_repositories(
    name = "swift_pkgs",
    dependencies = [
        spm_pkg(
            "https://github.com/apple/swift-log.git",
            exact_version = "1.4.2",
            products = ["Logging"],
        ),
        spm_pkg(
            "https://github.com/GetStream/stream-swift.git",
            name = "GetStream",
            exact_version = "2.2.2",
            products = [
                "GetStream",
                "Faye",
            ],
        ),
    ],
)
```

When I run `bazel test //...`, I get the following error:

```
/private/var/tmp/_bazel_chuck/acd478c94e4d22147ca64882e3ea61f8/sandbox/darwin-sandbox/3/execroot/simple_example/bazel-out/darwin-fastbuild/bin/external/swift_pkgs/spm_build/checkouts/stream-swift/Sources/Core/Client/Client.swift:9:8: error: no such module 'UIKit'
import UIKit
       ^
```

I poked around the package and realized that it is iOS-only. The `swift build` invocation that happens in `rules_spm` won't build the iOS package. I am investigating ways to support building non-MacOS platforms.

**Comment by sgammon** [comment]
@cgrindel i actually got this working -- by futzing around with the minimum iOS/macOS declaration, it eventually built.

i also had to work around a different issue which i will file separately, where the repo name has to match the name of the Swift package product. in these cases, forking the repo and renaming it was sufficient to get it to work, which is probably a bug. i'll explain on that other issue.

thank you for your quick response here, sorry i lost track of this ticket! really excited about this set of rules and i'd love to contribute if i could be helpful.
