### ISSUE TITLE
tools/spm_parser fails building with swiftc 5.7

### ISSUE THREAD

**Issue by gferon** [cgrindel/rules_spm#172]
We just switched to Xcode 14.0.0 and `spm_parser` now fails to build.

```
Building for debugging...
/Users/xdev/gabriel/rules_spm/tools/spm_parser/Sources/spm_parser/Dump.swift:8:8: error: ambiguous use of 'main'
struct Dump: ParsableCommand {
       ^
/Users/xdev/gabriel/rules_spm/tools/spm_parser/Sources/spm_parser/Dump.swift:8:8: error: ambiguous use of 'main'
struct Dump: ParsableCommand {
       ^
[2/3] Compiling spm_parser Dump.swift
```

I'm not exactly sure what could be going on, it might be an issue with a 3rd party dependency, but I feel like you're in a better place to give this a look 🙏🏼

**Comment by cgrindel** [comment]
@gferon I was not able to reproduce the issue after upgrading to Xcode 14.0. However, I ran into a similar issue with another project. In that project, I moved the main to an explicit main func. I applied the same change to this repo in #173. Can you give it a try?

**Comment by cgrindel** [comment]
jkj

**Comment by cgrindel** [comment]
@gferon I went ahead and merged the change. Please let me know if this addressed the error that you were seeing.

**Comment by gferon** [comment]
Yes it does, thank you very much!
