### ISSUE TITLE
unknown option --build-path

### ISSUE THREAD

**Issue by acecilia** [cgrindel/rules_spm#61]
Hi 👋 

When using the rules I am getting the following error:
```
Error in fail: Resolution of SPM packages for swift_pkgs failed.
error: unknown option --build-path; use --help to list available options
```

Issue seems to be when running `swift package resolve --build-path` here: https://github.com/cgrindel/rules_spm/blob/ade5756a5b20014fb6e69af8ce2f311294b477a6/spm/internal/spm_repositories.bzl#L479

Are there any minimum swift version requirements for the rules? Currently in my machine:
```
swift -version
Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
```

Thanks! 🙏

**Comment by cgrindel** [comment]
Yeah. I meant to add a `swift package --version` check. While I could probably work around the `--build-path` issue, there is another compatibility issue with the JSON that is generated by `swift package describe --type json`. Unless someone has a better idea, I will add an early check for `Swift Package Manager - Swift 5.4.0` or later.

**Comment by acecilia** [comment]
Makes sense, thanks!

**Comment by cgrindel** [comment]
I am going to reopen this issue to track the addition of the SPM version check.
